/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/model/Bubbles.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Bubble(props) {
  const { nodes, materials } = useGLTF('/model/Bubbles.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Frame_low.geometry} material={materials.GunGs} position={[0.19, 0.01, -0.2]} rotation={[1.49, -0.58, -0.76]} scale={0.63} />
    </group>
  )
}

useGLTF.preload('/model/Bubbles.glb')
