/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/model/household.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function HouseHold(props) {
  const { nodes, materials } = useGLTF("/model/household.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh1_Group1_Component_1_1_Model.geometry}
        material={materials.Material}
        position={[4.04, 0, 2.98]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.Hand_saw.geometry}
        material={materials.Material}
        position={[3.9, 0, 2.82]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.09}
      />
      <mesh
        geometry={nodes.Hoe.geometry}
        material={materials.Material}
        position={[-0.1, 0, 3.19]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={0.43}
      />
      <mesh
        geometry={nodes.Screwdriver.geometry}
        material={materials.Material}
        position={[3.76, 0, 2.82]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.11}
      />
      <mesh
        geometry={nodes.Wrench.geometry}
        material={materials.Material}
        position={[3.66, 0, 2.63]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.16}
      />
      <mesh
        geometry={nodes.watering_can.geometry}
        material={materials.Material}
        position={[-1.59, 0, 2.76]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.27}
      />
      <mesh
        geometry={nodes.Toolbox.geometry}
        material={materials.Material}
        position={[3.47, 0, 2.74]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.95}
      />
      <mesh
        geometry={nodes.Telescope.geometry}
        material={materials.Material}
        position={[1.88, 0.01, 2.41]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.58}
      />
      <mesh
        geometry={nodes.Ladder.geometry}
        material={materials.Material}
        position={[6.17, 0, -0.28]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.82}
      />
      <mesh
        geometry={nodes.Hand_rake.geometry}
        material={materials.Material}
        position={[0.13, 0, 2.81]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={0.17}
      />
      <mesh
        geometry={nodes.Caldron.geometry}
        material={materials.Material}
        position={[3.13, 0.01, 2.61]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.13}
      />
      <mesh
        geometry={nodes.Chandelier.geometry}
        material={materials.Material}
        position={[5.43, 0.02, 3.1]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.14}
      />
      <mesh
        geometry={nodes.Bird_House.geometry}
        material={materials.Material}
        position={[-2.19, 0.57, 1]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.11}
      />
      <mesh
        geometry={nodes.Dumbbell.geometry}
        material={materials.Material}
        position={[-1.5, 0, 1.99]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.19}
      />
      <mesh
        geometry={nodes.baseballBat.geometry}
        material={materials.Material}
        position={[4.21, -0.41, 2.37]}
        rotation={[Math.PI / 2, -0.73, -Math.PI / 2]}
        scale={0.11}
      />
      <mesh
        geometry={nodes.Trophy.geometry}
        material={materials.Material}
        position={[2.89, 0, 1.76]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.18}
      />
      <mesh
        geometry={nodes.Safe.geometry}
        material={materials.Material}
        position={[5.5, 0, 1.93]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.11}
      />
      <mesh
        geometry={nodes.Rubber_duck.geometry}
        material={materials.Material}
        position={[3.51, 0.53, -0.68]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.03}
      />
      <mesh
        geometry={nodes.Propane_tank.geometry}
        material={materials.Material}
        position={[0.24, 0, -0.32]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.21}
      />
      <mesh
        geometry={nodes.piggy_bank.geometry}
        material={materials.Material}
        position={[4.32, 0, 2.12]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.11}
      />
      <mesh
        geometry={nodes.Pumpkin.geometry}
        material={materials.Material}
        position={[2.47, 0, 2.56]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.33, 0.33, 0.29]}
      />
      <mesh
        geometry={nodes.Empty_box.geometry}
        material={materials.Material}
        position={[0.84, 0.01, 2.67]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.doll.geometry}
        material={materials.Material}
        position={[6.94, 0.49, 1.97]}
        scale={0.04}
      />
      <mesh
        geometry={nodes.Closed_umbrella.geometry}
        material={materials.Material}
        position={[8.66, 0.38, 1.37]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.13}
      />
      <mesh
        geometry={nodes.Present.geometry}
        material={materials.Material}
        position={[4.5, 0, 2.12]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.06}
      />
      <mesh
        geometry={nodes.wine_glass.geometry}
        material={materials.Material}
        position={[3.26, 0, 2.13]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.62}
      />
      <mesh
        geometry={nodes.Jar.geometry}
        material={materials.Material}
        position={[4.17, 0, 2.12]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.04}
      />
      <mesh
        geometry={nodes.Frying_pan.geometry}
        material={materials.Material}
        position={[-0.08, 0.51, -0.27]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Cup_of_tea.geometry}
        material={materials.Material}
        position={[3.42, 0, 2.12]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.03}
      />
      <mesh
        geometry={nodes.Candlestick.geometry}
        material={materials.Material}
        position={[5.67, 0.62, 1.08]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.Wall_corkboard_with_post_it_notes.geometry}
        material={materials.Material}
        position={[2.74, 0.02, 2.12]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.11}
      />
      <mesh
        geometry={nodes.Table_large_circular.geometry}
        material={materials.Material}
        position={[-2.56, 0, 2.12]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.36}
      />
      <mesh
        geometry={nodes.Table.geometry}
        material={materials.Material}
        position={[-0.11, 0, 2.03]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.61}
      />
      <mesh
        geometry={nodes.Stool.geometry}
        material={materials.Material}
        position={[1.65, 0, 1.7]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.15}
      />
      <mesh
        geometry={nodes.Rocking_chair.geometry}
        material={materials.Material}
        position={[1.06, 0, 1.77]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.69}
      />
      <mesh
        geometry={nodes.Mailbox.geometry}
        material={materials.Material}
        position={[-2.59, 0, 1]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.31}
      />
      <mesh
        geometry={nodes.Lamp_with_shade.geometry}
        material={materials.Material}
        position={[6.14, 0.51, 1.98]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.05}
      />
      <mesh
        geometry={nodes.Grandfathers_clock.geometry}
        material={materials.Material}
        position={[5, 0, 1.57]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.42}
      />
      <mesh
        geometry={nodes.Desk_lamp.geometry}
        material={materials.Material}
        position={[4.3, 0, 1.24]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.06}
      />
      <mesh
        geometry={nodes.Coat_rack.geometry}
        material={materials.Material}
        position={[8.68, 0, 1.33]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.26}
      />
      <mesh
        geometry={nodes.cabinet.geometry}
        material={materials.Material}
        position={[6.25, 0.02, 2.12]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.53}
      />
      <mesh
        geometry={nodes.Towel_rack.geometry}
        material={materials.Material}
        position={[4.86, 0, -0.52]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.hair_dryer.geometry}
        material={materials.Material}
        position={[1.87, 0.57, -0.55]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Bathtub.geometry}
        material={materials.Material}
        position={[3.93, 0, -0.4]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.9}
      />
      <mesh
        geometry={nodes.Toilet.geometry}
        material={materials.Material}
        position={[2.73, 0, -0.5]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.1}
      />
      <mesh
        geometry={nodes.Bathroom_sink.geometry}
        material={materials.Material}
        position={[1.99, 0.24, -0.45]}
        scale={0.17}
      />
      <mesh
        geometry={nodes.FruitBowl.geometry}
        material={materials.Material}
        position={[3.14, 0, 1.91]}
        scale={0.06}
      />
      <mesh
        geometry={nodes.Trashbin.geometry}
        material={materials.Material}
        position={[1.41, 0, -0.5]}
        scale={0.14}
      />
      <mesh
        geometry={nodes.Refrigirator.geometry}
        material={materials.Material}
        position={[0.87, 0, -0.38]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.Stove.geometry}
        material={materials.Material}
        position={[-0.24, -0.01, -0.4]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.Barbecue.geometry}
        material={materials.Material}
        position={[-1.13, 0, -0.28]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.05}
      />
      <mesh
        geometry={nodes.Treadmill.geometry}
        material={materials.Material}
        position={[-1.53, -0.05, 1.24]}
        rotation={[0.04, 0, 0]}
        scale={0.27}
      />
      <mesh
        geometry={nodes.Ceiling_Fan.geometry}
        material={materials.Material}
        position={[5.21, 0.14, 2.34]}
        scale={0.11}
      />
      <mesh
        geometry={nodes.Bed.geometry}
        material={materials.Material}
        position={[7.7, 0, 1.94]}
        scale={0.3}
      />
      <mesh
        geometry={nodes.Globe.geometry}
        material={materials.Material}
        position={[4.45, 0, 1.74]}
        scale={0.11}
      />
      <mesh
        geometry={nodes.Dresser.geometry}
        material={materials.Material}
        position={[5.71, 0, 1.11]}
        scale={0.14}
      />
      <mesh
        geometry={nodes.End_Table.geometry}
        material={materials.Material}
        position={[0.29, 0, 1]}
        scale={0.26}
      />
      <mesh
        geometry={nodes.Armchair.geometry}
        material={materials.Material}
        position={[-0.55, 0, 0.99]}
        scale={0.22}
      />
      <mesh
        geometry={nodes.Couch.geometry}
        material={materials.Material}
        position={[1.72, 0, 1.06]}
        scale={0.32}
      />
      <mesh
        geometry={nodes.Books.geometry}
        material={materials.Material}
        position={[4.96, 1.06, 0.93]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.Bookshelf.geometry}
        material={materials.Material}
        position={[5.07, 0, 0.92]}
        scale={0.41}
      />
      <mesh
        geometry={nodes.Alarm_Clock.geometry}
        material={materials.Material}
        position={[3.28, 0, 1.67]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.06}
      />
      <mesh
        geometry={nodes.Desk_Fan.geometry}
        material={materials.Material}
        position={[4.23, 0, 1.95]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={0.11}
      />
      <mesh
        geometry={nodes.Printer.geometry}
        material={materials.Material}
        position={[3.28, 0.43, 0.91]}
        scale={0.04}
      />
      <mesh
        geometry={nodes.Desk_lamp001.geometry}
        material={materials.Material}
        position={[4.3, 0, 0.99]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.05}
      />
      <mesh
        geometry={nodes.Computer.geometry}
        material={materials.Material}
        position={[4.17, 0.44, 1.01]}
        scale={0.17}
      />
      <mesh
        geometry={nodes.Mouse.geometry}
        material={materials.Material}
        position={[3.94, 0.44, 1.18]}
        scale={0.04}
      />
      <mesh
        geometry={nodes.Keyboard.geometry}
        material={materials.Material}
        position={[3.67, 0.43, 1.18]}
        scale={[0.07, 0.01, 0.07]}
      />
      <mesh
        geometry={nodes.Monitor.geometry}
        material={materials.Material}
        position={[3.67, 0.44, 1.01]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.11}
      />
      <mesh
        geometry={nodes.Chair.geometry}
        material={materials.Material}
        position={[2.77, 0, 1.23]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.2}
      />
      <mesh
        geometry={nodes.Desk.geometry}
        material={materials.Material}
        position={[3.44, 0, 1.04]}
        scale={0.3}
      />
      <mesh
        geometry={nodes.Flowers.geometry}
        material={materials.Material}
        position={[3.57, 0, 1.67]}
        scale={[0.01, 0.17, 0.01]}
      />
      <mesh
        geometry={nodes.Headphones.geometry}
        material={materials.Material}
        position={[3.58, 0, 1.82]}
        scale={0.03}
      />
      <mesh
        geometry={nodes.Mug_with_office_tools.geometry}
        material={materials.Material}
        position={[3.59, 0, 2.2]}
        scale={0.05}
      />
      <mesh
        geometry={nodes.Chips.geometry}
        material={materials.Material}
        position={[3.41, 0, 2.04]}
        scale={[0.03, 0.04, 0.04]}
      />
      <mesh
        geometry={nodes.Hamburger.geometry}
        material={materials.Material}
        position={[3.54, 0, 1.98]}
        scale={0.05}
      />
      <mesh
        geometry={nodes.Soda_Can.geometry}
        material={materials.Material}
        position={[3.43, 0, 1.88]}
        rotation={[Math.PI, -0.17, Math.PI]}
        scale={[0.03, 0.04, 0.03]}
      />
      <mesh
        geometry={nodes.Stapler.geometry}
        material={materials.Material}
        position={[3.68, 0, 1.97]}
        scale={0.06}
      />
      <mesh
        geometry={nodes.Potted_Plant000.geometry}
        material={materials.Material}
        position={[3.87, 0, 1.77]}
        scale={0.06}
      />
      <mesh
        geometry={nodes.Painting.geometry}
        material={materials.Material}
        position={[3.93, 0, 2.1]}
        scale={0.13}
      />
      <mesh
        geometry={nodes.Tissue_Box.geometry}
        material={materials.Material}
        position={[3.75, 0, 2.2]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.1, 0.1, 0.04]}
      />
      <mesh
        geometry={nodes.Floor.geometry}
        material={nodes.Floor.material}
        scale={87.48}
      />
      <mesh
        geometry={nodes.Floor001.geometry}
        material={nodes.Floor001.material}
        scale={176.21}
      />
    </group>
  );
}

useGLTF.preload("/model/household.glb");
